### ISSUE TITLE
Error in execution “ python3 main.py --load_config=unet_vgg16_train.yaml train Train VGG16UNET”

### ISSUE THREAD

**Issue by ytgcljj** [MSiam/TFSegmentation#3]
testc@testc2018:~/TFSegmentation$ python3 main.py --load_config=unet_vgg16_train.yaml train Train VGG16UNET

Parsing Arguments..

Using this arguments check it

batch_size -- 3 --
batchnorm_enabled -- True --
bias -- 0.0 --
config_path -- unet_vgg16_train.yaml --
data_dir -- data/full_cityscapes_res --
data_mode -- experiment --
exp_dir -- unet_vgg16 --
freeze_encoder -- False --
img_height -- 512 --
img_width -- 1024 --
learning_decay -- 1e-07 --
learning_decay_every -- 100 --
learning_rate -- 0.0001 --
max_to_keep -- 2 --
mode -- train --
model -- VGG16UNET --
momentum -- 0.9 --
num_channels -- 3 --
num_classes -- 20 --
num_epochs -- 200 --
num_groups -- 3 --
operator -- Train --
out_dir -- unet_vgg16 --
pretrained_path -- pretrained_weights/vgg16.npy --
random_cropping -- False --
save_every -- 5 --
shuffle -- True --
test_every -- 5 --
verbose -- False --
weight_decay -- 4e-05 --
weighted_loss -- True --

Traceback (most recent call last):
  File "main.py", line 19, in <module>
    main()
  File "main.py", line 14, in main
    agent = Agent(args)
  File "/home/testc/TFSegmentation/agent.py", line 36, in __init__
    self.model = globals()[args.model]
KeyError: 'VGG16UNET'

**Comment by MG2033** [comment]
You should go to models/[model_name.py]. Then, you should get the model class name. In your case, it's UNetVGG16 not VGG16UNET. Maybe you're using an old name of the class.

**Comment by ytgcljj** [comment]
thank you help  me 
I re  updated TFSegmentation, and now I report this mistake again

testc@testc2018:~/TFSegmentation$ python3 main.py --load_config=unet_vgg16_train.yaml train Train UNetVGG16

Parsing Arguments..

Using this arguments check it

batch_size -- 3 --
batchnorm_enabled -- True --
bias -- 0.0 --
config_path -- unet_vgg16_train.yaml --
data_dir -- full_cityscapes_res --
data_mode -- experiment --
exp_dir -- unet_vgg16 --
freeze_encoder -- False --
img_height -- 512 --
img_width -- 1024 --
learning_decay -- 1e-07 --
learning_decay_every -- 100 --
learning_rate -- 0.0001 --
max_to_keep -- 2 --
mode -- train --
model -- UNetVGG16 --
momentum -- 0.9 --
num_channels -- 3 --
num_classes -- 20 --
num_epochs -- 200 --
num_groups -- 3 --
operator -- Train --
out_dir -- unet_vgg16 --
pretrained_path -- pretrained_weights/vgg16.npy --
random_cropping -- False --
save_every -- 5 --
shuffle -- True --
test_every -- 5 --
verbose -- False --
weight_decay -- 4e-05 --
weighted_loss -- True --



Agent is running now...


2018-03-15 10:10:24.255299: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-03-15 10:10:24.255329: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-03-15 10:10:24.255345: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-03-15 10:10:24.255349: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2018-03-15 10:10:24.255354: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    main()
  File "main.py", line 15, in main
    agent.run()
  File "/home/testc/TFSegmentation/utils/misc.py", line 18, in timed
    result = f(*args, **kwargs)
  File "/home/testc/TFSegmentation/agent.py", line 85, in run
    self.build_model()
  File "/home/testc/TFSegmentation/utils/misc.py", line 18, in timed
    result = f(*args, **kwargs)
  File "/home/testc/TFSegmentation/agent.py", line 46, in build_model
    self.model = self.model(self.args)
  File "/home/testc/TFSegmentation/models/unet_vgg16.py", line 11, in __init__
    super().__init__(args, phase=phase)
TypeError: __init__() got an unexpected keyword argument 'phase'

**Comment by MSiam** [comment]
I fixed the issue you should be able to run it now.

**Comment by ytgcljj** [comment]
File "main.py", line 19, in <module>
    main()
  File "main.py", line 15, in main
    agent.run()
  File "/home/testc/TFSegmentation/utils/misc.py", line 18, in timed
    result = f(*args, **kwargs)
  File "/home/testc/TFSegmentation/agent.py", line 85, in run
    self.build_model()
  File "/home/testc/TFSegmentation/utils/misc.py", line 18, in timed
    result = f(*args, **kwargs)
  File "/home/testc/TFSegmentation/agent.py", line 46, in build_model
    self.model = self.model(self.args)
  File "/home/testc/TFSegmentation/models/unet_vgg16.py", line 11, in __init__
    super().__init__(args)
  File "/home/testc/TFSegmentation/models/basic/basic_model.py", line 37, in __init__
    self.params.class_weights= np.load(self.args.data_dir+'weights.npy')
  File "/usr/local/lib/python3.5/dist-packages/numpy/lib/npyio.py", line 370, in load
    fid = open(file, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/testc/TFSegmentation/data/full_cityscapes_res/weights.npy
