### ISSUE TITLE
Resource exhausted: OOM

### ISSUE THREAD

**Issue by leonard10000gn** [MSiam/TFSegmentation#37]
2018-08-06 08:21:31.998637: W tensorflow/core/common_runtime/bfc_allocator.cc:279] ****************************************************************************************************
2018-08-06 08:21:31.998655: W tensorflow/core/framework/op_kernel.cc:1318] OP_REQUIRES failed at gpu_swapping_kernels.cc:72 : Resource exhausted: OOM when allocating tensor with shape[5,32,512,1024] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Traceback (most recent call last):
  File "/root/anaconda3/envs/scc_py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/root/anaconda3/envs/scc_py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/root/anaconda3/envs/scc_py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[5,64,256,512] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[Node: network/train-operation/gradients/AddN_14-0-TransposeNHWCToNCHW-LayoutOptimizer = Transpose[T=DT_FLOAT, Tperm=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](network/train-operation/gradients/network/upscale_4/upscale4/batch_normalization/cond/FusedBatchNorm_1/Switch_grad/cond_grad, PermConstNHWCToNCHW-LayoutOptimizer)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[Node: network/pixel_wise_accuracy/Mean/_1157 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_19236_network/pixel_wise_accuracy/Mean", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 19, in <module>
    main()
  File "main.py", line 15, in main
    agent.run()
  File "/data/scc/TFSegmentation/utils/misc.py", line 18, in timed
    result = f(*args, **kwargs)
  File "/data/scc/TFSegmentation/agent.py", line 96, in run
    self.train()
  File "/data/scc/TFSegmentation/agent.py", line 139, in train
    self.operator.train()
  File "/data/scc/TFSegmentation/train/train.py", line 513, in train
    feed_dict=feed_dict)
  File "/root/anaconda3/envs/scc_py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/root/anaconda3/envs/scc_py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/root/anaconda3/envs/scc_py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/root/anaconda3/envs/scc_py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[5,64,256,512] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[Node: network/train-operation/gradients/AddN_14-0-TransposeNHWCToNCHW-LayoutOptimizer = Transpose[T=DT_FLOAT, Tperm=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](network/train-operation/gradients/network/upscale_4/upscale4/batch_normalization/cond/FusedBatchNorm_1/Switch_grad/cond_grad, PermConstNHWCToNCHW-LayoutOptimizer)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[Node: network/pixel_wise_accuracy/Mean/_1157 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_19236_network/pixel_wise_accuracy/Mean", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

I change batch_size to 1, but it also occur OOM

**Comment by moemen95** [comment]
Please tell the me your machine specifications

**Comment by Davidnet** [comment]
That usually refers that your gpu memory is fully allocated, either you do not have sufficient memory for training or inference, or something else is eating your GPU memory.
