### ISSUE TITLE
What's wrong with me ?

### ISSUE THREAD

**Issue by 18605973470** [MSiam/TFSegmentation#56]
Initializing the variables of the model
Initialization finished
   [-] init_model : 1.16156 sec, which is 0.01936 mins, which is 0.00032 hours
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    main()
  File "main.py", line 15, in main
    agent.run()
  File "/media/arch760/My Passport/TFSegmentation/utils/misc.py", line 18, in timed
    result = f(*args, **kwargs)
  File "/media/arch760/My Passport/TFSegmentation/agent.py", line 88, in run
    self.operator = self.operator(self.args, self.sess, self.model, self.model)
  File "/media/arch760/My Passport/TFSegmentation/train/train.py", line 50, in __init__
    super().__init__(args, sess, train_model, test_model)
  File "/media/arch760/My Passport/TFSegmentation/train/basic_train.py", line 39, in __init__
    save_relative_paths=True)
  File "/home/arch760/.local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1338, in __init__
    self.build()
  File "/home/arch760/.local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1347, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/arch760/.local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1384, in _build
    build_save=build_save, build_restore=build_restore)
  File "/home/arch760/.local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 813, in _build_internal
    saveables = self._ValidateAndSliceInputs(names_to_saveables)
  File "/home/arch760/.local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 661, in _ValidateAndSliceInputs
    names_to_saveables = BaseSaverBuilder.OpListToDict(names_to_saveables)
  File "/home/arch760/.local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 638, in OpListToDict
    name)
ValueError: At least two variables have the same name: network/conv1_x/bn1/mu

**Comment by erolrecep** [comment]
Which version tensorflow do you use? I've faced the same issue when I was trying to run with v1.7.1 .

**Comment by 18605973470** [comment]
@erolrecep  
1.12.0 ...

**Comment by erolrecep** [comment]
On requirements files they say 1.3.0 for tensorflow-gpu, 1.4.0 for tensorflow.
