### ISSUE TITLE
Problems running test and inference with Shufflenet

### ISSUE THREAD

**Issue by Zitzo** [MSiam/TFSegmentation#61]
Hello, I'm interested in using this network with my own dataset for real time segmentation on a jetson TX2. Previous to that I want to see the performance of the program running the examples you give, so that I can check the fps I get on the Jetson.

My problem appears when I run:
python3 main.py --load_config=fcn8s_shufflenet_test.yaml test Train FCN8sShuffleNet 
or 
python3 main.py --load_config=fcn8s_shufflenet_test.yaml inference Train FCN8sShuffleNet. 

I get an error saying that the archives X_test.npy, Y_test.npy and ynames_test.npy don't exist. These issues are actually true, because these .npy do not appear in the full_cityscapes_res.zip you can download from google drive. I don't know if this is an error and you can past arround that downloading the data from another source or in another way.

The problem is that even if I change this data with the validation or training data that is contained in full_cityscapes_res to avoid this error I get another error in line 907 of train_py: 

Traceback (most recent call last):
  File "main.py", line 19, in <module>
    main()
  File "main.py", line 15, in main
    agent.run()
  File "/home/alejandro/Segmentation/TFSegmentation/utils/misc.py", line 18, in timed
    result = f(*args, **kwargs)
  File "/home/alejandro/Segmentation/TFSegmentation/agent.py", line 107, in run
    self.test()
  File "/home/alejandro/Segmentation/TFSegmentation/agent.py", line 146, in test
    self.operator.test(pkl)
  File "/home/alejandro/Segmentation/TFSegmentation/train/train.py", line 742, in test
    y_batch = self.test_data['Y'][idx:idx + 1]
KeyError: 'Y'

Telling me that the array doesn't have any Y data, only X. I can't come over this error and therefore I can't run the program to discover how many fps it gets. I tried to remove this line or to fill it with the X data but I still get errors. Maybe the reason of these errors is that I need the .npy data that i don't have.

I also discovered that in line 891 of train.py a exit(1) appeared (also mentioned in this issues: https://github.com/MSiam/TFSegmentation/issues/55), with this exit the program runs until it gets to that point but it's useless for what I'm trying to check. I would also like to know what this exit stands for, I commented it so that the program runs completely.  

Could someone help me to solve these errors? These is not even a part of what I'm trying to achieve using these repository, it's only a test for checking the performance and it's really demotivating to get these errors. If i can get over it I would like to ask how to use my dataset on this repository and which annotation tool you recommend for creating my labels.

For your information I'm using tensorflow-gpu 1.3, as recommended, with cuDNN 6 and python3 on a GTX 1070.

I will appreciate any help you can give me. 

Thank you all in advance.

**Comment by moemen95** [comment]
WHat is your image resolution?!
